# Generated by Django 5.1 on 2024-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=6)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('promocion', models.CharField(max_length=100)),
                ('colecciones', models.CharField(max_length=50)),
                ('novedades', models.CharField(max_length=75)),
            ],
        ),
    ]
